### ISSUE TITLE
Debarcer group function does not check for empty regions

### ISSUE THREAD

**Issue by prisnir** [oicr-gsi/debarcer#206]
Debarcer group function fails with errors when it encounters a region bed with no reads in the bam. 
I had assigned a small python fix for myself when I implemented this myself; 

> def checkReg(bam, region):
>     status = []
>     chrom = region.split(":")[0]
>     spos = int(region.split(":")[1].split("-")[0])
>     epos = int(region.split(":")[1].split("-")[1])
>     bam_file = pysam.AlignmentFile(bam, "rb")
>     reads = bam_file.fetch(chrom, spos, epos)
>     for read in reads:
>         if read:
>             status.append(True)
>         else:
>             status.append(False)
>     return (status)

before calling group and collapse for a region:

> for region in part:
>             status = checkReg(bam, region)
>             if not status:
>                 continue

Can something similar be introduced as a part of group? 
Where it checks if the bam file has enough coverage before grouping

**Comment by rjovelin** [comment]
An assertion error is thrown during grouping when no UMIs are found in a genomic region
This assertion statement is in umi_network_collapse.py in code borrowed from UMI-tools

```
[2020-09-08 13:21:05] Grouping UMIs...
Counting UMIs...
Clustering UMIs...
Traceback (most recent call last):
  File "/u/rjovelin/debarcer_rjdev/debarcer/debarcer/debarcer.py", line 806, in <module>
    args.func(args)
  File "/u/rjovelin/debarcer_rjdev/debarcer/debarcer/debarcer.py", line 154, in group_umis
    umi_families, umi_groups, umi_positions, mapped_reads = get_umi_families(contig, region_start, region_end, bam_file, pos_threshold, dist_threshold, args.ignore, args.truncate, args.separator)
  File "/u/rjovelin/debarcer_rjdev/debarcer/debarcer/src/umi_error_correct.py", line 286, in get_umi_families
    umi_groups = cluster_umis(umis, counts, dist_threshold)
  File "/u/rjovelin/debarcer_rjdev/debarcer/debarcer/src/umi_error_correct.py", line 90, in cluster_umis
    umi_groups = clusterer(umis, counts, dist_threshold)
  File "/u/rjovelin/debarcer_rjdev/debarcer/debarcer/src/umi_network_collapse.py", line 216, in __call__
    assert len_umis, "No UMIs present(!)"
AssertionError: No UMIs present(!)

```

**Comment by rjovelin** [comment]
A couple of comments:
1) It is assumed users have identified regions of coverage before running debarcer 
2) ```debarcer bed``` command can identify regions of coverage and generate a bed if such regions are unknown

**Comment by rjovelin** [comment]
The proposed logic loops over each read in the region, which is not efficient.
Instead I introduced a new parameter in the ```group``` and ```run``` commands, ```readcount``` and method ```count``` on pysam ```AlignmentFile``` object to count the number of mapped reads in a given genomic region given by contig, start and stop.
Grouping is done if the number of reads in region is greater than the parameter ```readcount```. Default value is 0.
Collapse will throw a ValueError if outpuf files from grouping are not generated.
