### ISSUE TITLE
debarcer with targeted capture

### ISSUE THREAD

**Issue by abolia** [oicr-gsi/debarcer#75]
Hi, 

I came across this software and I am interested in using it to analyze my targeted capture data with dual indices. I have two questions:
1) Can I use debarcer for targeted capture data with dual indices?
2) What type of molecular barcodes/UMI chemistry does debarcer work with?

Thank you so much for your help.
Ashini

**Comment by morgantaschuk** [comment]
Hi Ashini,

Debarcer accompanies the protocol described in the paper [Simple, multiplexed, PCR-based barcoding of DNA enables sensitive mutation detection in liquid biopsies using sequencing](https://doi.org/10.1093/nar/gkw224) which describes a technique called SimSenSeq. We're in the process (slowly) of modifying it to work with other molecular barcoding technologies, in particular HaloPlex (in the gsidev branch but still a prototype). 

@pmkrzyzanowski was one of the original authors and he can answer any more questions you have.

-Morgan

**Comment by abolia** [comment]
Thanks @morgantaschuk for your reply. Do you plan to bring a demultiplexing strategy for dual indexed libraries as well?

Thanks,
Ashini

**Comment by morgantaschuk** [comment]
@pmkrzyzanowski or @lheisler, could you answer Ashini's question?

**Comment by lheisler** [comment]
Hi Ashini,  There is intention to develop this tool further to handle different methods of barcoding, including duel indices, but I could not at this point give you a timeline.  To be clear : this not addressing demultiplexing. It is barcoding for identification of pcr duplications, and implementation of error correction.

**Comment by rjovelin** [comment]
Currently debarcer can handle SiMSen-Seq paired and single end reads, HaloPlex, Sureselect and Epic-DS
