### ISSUE TITLE
test data for Debarcer

### ISSUE THREAD

**Issue by tyrosine** [oicr-gsi/debarcer#85]
Hi,
I want to have a try on this nice package, and have installed successfully. According to the Nature Protocol paper, there should be a bundled test data set, however, I cannot find it. Could you please let me know where to get the test data? thanks! 

Adrian

**Comment by tyrosine** [comment]
Hi Lawrence,
I managed to install the previous version v0.3.1, and run the test data but get the following error message, could you please take a look? thanks!
*******************************************
[yit2001@grcf test_tools]$ sh runTest.sh
Running Debarcer in /home/yit2001/Softwares/debarcer/test_results
Running debarcer...
cat: /home/yit2001/Softwares/debarcer//.git/d0d6ae85f0172cf2a401f6845d12b492602f5202: No such file or directory
Sourcing ~/.debarcer
/home/yit2001/Softwares/debarcer/runDebarcer.sh: line 103: /home/yit2001/.debarcer: No such file or directory
Sourcing ~/.debarcer
/home/yit2001/Softwares/debarcer//src//runBWA.sh: line 4: /home/yit2001/.debarcer: No such file or directory
Running bwa/0.7.12 on Sample Sample_Test using fastq: Sample_Test.R1.fastq.gz
bwa using  processors
/home/yit2001/Softwares/debarcer//src//runBWA.sh: line 14: /bwa: No such file or directory

**Comment by rjovelin** [comment]
Unresolved. Closing issues unrelated to debarcer 2
