### ISSUE TITLE
two quick questions about the new version

### ISSUE THREAD

**Issue by tyrosine** [oicr-gsi/debarcer#86]
Hi,
I cannot get the old version(v0.3.1) to work. So I plan to try your pre-released new version.
Just two quick questions:
1. I need to use some other package like BWA to run the second step of  the typical workflow, right?
## produces: bam_file.bam, bam_file.bam.bai

2.  Does the region parameter  (-r chrN:posA-posB) refer to the target region? If so, given there are several  target genes, can they be  put together as a text file?(something like bed file)
Thanks a lot!
Best,
Adrian

**Comment by lheisler** [comment]
H Adrian,
1. After extraction of the uids, you'll need to an align (we use bwa mem) against the reference genome prior to collapsing and calling variants.  
2. Consensus calls based on uids is done over discrete target regions.   I believe the current implementation will only take a single region.  You'd need to write your own script to work with multiple regions, running the tool in parallel for each region, then combining the results afterwards.  

note that I'm in the process  now of reviewing much of the work on this version, which was mostly done by a co-op student on my direction.  I'm hoping in the next month to test, debug and further document.  Please feel free to use and identify issues you are finding.

**Comment by tyrosine** [comment]
Hi Lawrence,
Got it,  thank you so much for the prompt responses! Will let you know if I get any problems.
Best,
Adrian

**Comment by rjovelin** [comment]
Multiple regions are now allowed by passing a bed file to the run sub-module, providing users have access to SGE. This will launch jobs to run group and collapse in parallel on each region.
There is also an option to merge outputs from group and collapse, merging specifically the consensus files and the data files
