### ISSUE TITLE
Checking UMI configuration file

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/debarcer#88]
The UMI configuration file has named configurations as
[NAME]
this appears to have to be all uppercase, although not clear in the documentation.  Can either keep as this, but update documentation and add in a cheque to ensure this is so, then provide error if not. Currently the script fails with a traceback.

In fact, many errors in the UMI config result in the program crashing.  There should be a check on its contents before attempting to use it.

I expect also that the methodology can be extended here. For instance, 
1. currently expecting when UMIs are in multiple reads, that each are configured the same
2. Assumes that UMI is at the start of any read.  It might better to indicate a position and a length. This will also allow for trimming of the UMI if desired.  (I had thought initially that this was what UMI_LOCS was for, but now see that it is for which reads.  I think this can be named better)

**Comment by rjovelin** [comment]
There is now a check on the library prep ini file. The function checks the ini format and the parameter values for the different library types
