### ISSUE TITLE
debarcer preprocess -o ignored?

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/debarcer#89]
adding -o fastq to the command does not save data in the fastq folder, but rather in the current folder.
Possibly its looking for an absolute path
Also, files are simply called fastq.R1.fastq.gz and fastq.R2.fastq.gz.  These should either inherit the names of the source files or there should be a way to specify how they should be named.

**Comment by rjovelin** [comment]
There is an issue with the -o parameter. 
It is meant to point to a directory for some functions but for others it acts as a prefix  to which R1.fastq.gz and fastq.R2.fastq.gz are appended.
Will review and fix this bug

**Comment by rjovelin** [comment]
Setting up the output_path in the config as output_path=/scratch2/groups/gsi/bis/debarcer2/ does not produce the expected output files. No error is recorded in the log:
Preprocessing reads...
Complete. Output written to /scratch2/groups/gsi/bis/debarcer2.

**Comment by rjovelin** [comment]
Added an optional prefix parameter to name reheadered fastqs: prefix.umi.reheadered_RN.fastq.gz
If prefix is not specified, reheadered files inherit the name of the source files.
Also changed the parameter out_path to require a directory
