### ISSUE TITLE
add functionality to identify regions of coverage

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/debarcer#90]
currently, one needs to provide intervals where the program will look for UMIs, to group and collapse data in each region.  These can be run in parallel.  It would be good to include the ability to assess the aligned sequence to define intervals where there are reads found, which one can then use as input for the group and collapse commands

**Comment by rjovelin** [comment]
Added a sub-module bed that scans the bam for regions of coverage.
It will generate a bed file with all genomic intervals of size equal or greater to parameter region_length for which all positions have read depth equal or greater than parameter min_cov.

python debarcer bed -h
-b, --Bamfile: Path to the BAM file, required
-bd, --Bedfile: Path to the output bed file, required
-mv, --MinCov: Minimum read depth value at all positions in genomic interval, required
-r, --RegionSize: Minimum length of the genomic interval (in bp), required
-m, --MaxDepth: Maximum read depth. Default is 1000000
-io, --IgnoreOrphans: Ignore orphans (paired reads that are not in a proper pair). Default is False
-stp, --Stepper: Filter or include reads in the pileup. Default is nofilter
