### ISSUE TITLE
Installation and usage issues

### ISSUE THREAD

**Issue by veseshan** [oicr-gsi/debarcer#91]
I installed (using pip install) debarcer (v2.0.0) on a Linux server running Ubuntu 16.04 with python3.6.5 (installed from a PPA). The package resides is /usr/local/lib/python3.6/dist-packages. If I try to run it from my home directory I get this error

```
ebadmin@eb-z800:~$ python3.6 debarcer.py -h
python3.6: can't open file 'debarcer.py': [Errno 2] No such file or directory
```
When run from the package directory I get a different error

```
ebadmin@eb-z800:/usr/local/lib/python3.6/dist-packages/debarcer$ python3.6 debarcer.py -h
Traceback (most recent call last):
  File "debarcer.py", line 7, in <module>
    from src.handle_args import handle_arg
ModuleNotFoundError: No module named 'src'
```

When I cloned the repository and run the command from the debarcer directory I get the proper help output. 

```
ebadmin@eb-z800:~/debarcer/debarcer$ python3.6 debarcer.py -h
usage: debarcer.py [-h] {preprocess,group,collapse,call} ...

A package for De-Barcoding and Error Correction of sequencing data containing
molecular barcodes.

positional arguments:
  {preprocess,group,collapse,call}
    preprocess          Preprocess mode for processing fastq files.
    group               Groups and error-corrects UMIs into families.
    collapse            Base collapsing from given UMI families file.
    call                Variant calling from analyzed BAM file.

optional arguments:
  -h, --help            show this help message and exit
```
Can you provide some guidance as to how I should be installing and using this package? 

Thanks.

**Comment by lheisler** [comment]
Hi Veseshan,
I'll be taking a closer look at this soon, testing on a separate system from where it was developed.  
You do appear though to have a way to run the tool by moving into the cloned directory. I'd stick with that for now.
Note also that I'm addressing a number of other issues with functionality, tracking them on this site

**Comment by rjovelin** [comment]
We release a new version debarcer v2.0.3-alpha, available on Pypi with a number of bug fixes including src and utils modules not included in the previous versions. 
Run the following command to install debarcer v2.0.3-alpha:
``pip install debarcer``
Or to install debarcer under a specific python version:
``python -m pip install debarcer`` 

To run debarcer, you need to specify the path to the debarcer.py script:
``python /usr/local/lib/python3.6/dist-packages/debarcer.py -h``
If you run it from the directory where debarcer.py is located, simply run:
``python debarcer.py -h``

Alternatively, set up the PYTHONPATH environment variable to run your script from any directory
Write the following command in your .bashrc
PYTHONPATH=${PYTHONPATH}:/usr/local/lib/python3.6/dist-packages/
export PYTHONPATH

Then run debarcer with the following command (note the absence of .py extension)
``python -m debarcer -h``
