### ISSUE TITLE
issue with Error-correct and group UMIs into families step

### ISSUE THREAD

**Issue by tyrosine** [oicr-gsi/debarcer#92]
Hi Lawrence,
I have succefully processed fastq files, and prepared bam file, now get an issue in group UMI step. Could you please take a look? thanks!

Here are the error message:
*******************************
File "/home/yit2001/Softwares/debarcer_master/debarcer/debarcer/debarcer.py", line 130
    print("ERR: Unable to load .umis file.", file=sys.stderr)
                                                 ^
SyntaxError: invalid syntax
*******************************

Here is my code:
#######################
python /home/yit2001/Softwares/debarcer_master/debarcer/debarcer/debarcer.py group -r chr18:60985820-60985920  -c /data2/Users/yit2001/DNASeq_ana/SiMSen_data/test_data/sample_config.ini  -b /data2/Users/yit2001/DNASeq_ana/SiMSen_data/test_data/output/25-S.psorted.bam  -o /data2/Users/yit2001/DNASeq_ana/SiMSen_data/test_data/output
#######################

Best,
Adrian

**Comment by rjovelin** [comment]
I replaced the pickle files with a json file storing a dictionary with information about umi groups and families in the form {umi_sequence: {'parent': parent_umi_sequence, 'positions': {start: count}}}
